import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { motion, AnimatePresence } from 'motion/react';
import { X, CheckCircle2, Minus, CircleDashed } from 'lucide-react';

interface Participant {
  id: string;
  name: string;
  minutesPresent: number;
}

const mockParticipants: Participant[] = [
  { id: '1', name: 'Matt Chen', minutesPresent: 12 },
  { id: '2', name: 'Alex Rivera', minutesPresent: 4 },
  { id: '3', name: 'Jordan Lee', minutesPresent: 0 },
  { id: '4', name: 'Sam Taylor', minutesPresent: 31 },
];

export function FocusRoom() {
  const navigate = useNavigate();
  const [timerMinutes, setTimerMinutes] = useState(25);
  const [timerSeconds, setTimerSeconds] = useState(0);
  const [isTimerRunning, setIsTimerRunning] = useState(false);
  const [myTimePresent, setMyTimePresent] = useState(0);
  const [showExitModal, setShowExitModal] = useState(false);
  const [selectedFeeling, setSelectedFeeling] = useState<string | null>(null);

  // Collective focus counter (mock)
  const totalHoursToday = 6;

  // Timer countdown
  useEffect(() => {
    if (!isTimerRunning) return;

    const interval = setInterval(() => {
      if (timerSeconds === 0) {
        if (timerMinutes === 0) {
          // Timer complete
          setIsTimerRunning(false);
          return;
        }
        setTimerMinutes((prev) => prev - 1);
        setTimerSeconds(59);
      } else {
        setTimerSeconds((prev) => prev - 1);
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [isTimerRunning, timerMinutes, timerSeconds]);

  // Track time present
  useEffect(() => {
    const interval = setInterval(() => {
      setMyTimePresent((prev) => prev + 1);
    }, 60000); // Every minute

    return () => clearInterval(interval);
  }, []);

  const handleStartTimer = () => {
    setIsTimerRunning(true);
  };

  const handleRestartTimer = () => {
    setTimerMinutes(25);
    setTimerSeconds(0);
    setIsTimerRunning(true);
  };

  const handleExtendTimer = () => {
    setTimerMinutes((prev) => prev + 10);
  };

  const handleLeave = () => {
    setShowExitModal(true);
  };

  const handleExitComplete = () => {
    if (selectedFeeling) {
      navigate('/home');
    }
  };

  const formatTime = () => {
    return `${timerMinutes.toString().padStart(2, '0')}:${timerSeconds.toString().padStart(2, '0')}`;
  };

  const getTimeLabel = (minutes: number) => {
    if (minutes === 0) return 'just joined';
    if (minutes < 60) return `${minutes} min`;
    const hours = Math.floor(minutes / 60);
    const mins = minutes % 60;
    return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
  };

  // Sort participants by time present
  const sortedParticipants = [...mockParticipants].sort((a, b) => b.minutesPresent - a.minutesPresent);

  return (
    <div className="min-h-screen" style={{ backgroundColor: '#F2F1EF' }}>
      <div className="max-w-4xl mx-auto px-4 py-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-[32px] font-bold text-[#464A63]">Live Focus Room</h1>
            <p className="text-[#4A5565] text-sm mt-1">Drop in, focus, leave when ready</p>
          </div>
          <button
            onClick={handleLeave}
            className="px-4 py-2 rounded-[20px] text-[#464A63] border-2 border-[#464A63] hover:bg-[#464A63] hover:text-white transition-all"
          >
            Leave Room
          </button>
        </div>

        {/* Collective Focus Counter */}
        <div className="glass-card p-6 text-center" style={{ borderTop: '4px solid #DAE77B' }}>
          <div className="text-sm text-[#4A5565] mb-2">Collective Focus Today</div>
          <div className="text-3xl font-bold text-[#464A63] mb-1">{totalHoursToday} hours</div>
          <div className="text-xs text-[#4A5565]">Generated by this room</div>
        </div>

        {/* Personal Timer */}
        <div className="glass-card p-8">
          <h2 className="text-xl font-semibold text-[#464A63] mb-6 text-center">Your Personal Timer</h2>
          
          <div className="text-center mb-6">
            <div className="text-[80px] font-bold text-[#464A63] leading-none mb-4">
              {formatTime()}
            </div>
            
            {!isTimerRunning && timerMinutes === 25 && timerSeconds === 0 ? (
              <div className="flex flex-col items-center">
                <button
                  onClick={handleStartTimer}
                  className="px-8 py-3 rounded-[20px] text-white text-lg font-semibold transition-all hover:opacity-90"
                  style={{ backgroundColor: '#CD7542' }}
                >
                  Start 25 Minutes
                </button>
                <p className="text-sm text-[#4A5565] italic mt-3">Starting is the hardest part.</p>
              </div>
            ) : !isTimerRunning ? (
              <div className="space-x-3">
                <button
                  onClick={handleRestartTimer}
                  className="px-6 py-2 rounded-[20px] text-white transition-all"
                  style={{ backgroundColor: '#464A63' }}
                >
                  Restart
                </button>
              </div>
            ) : (
              <div className="space-x-3">
                <button
                  onClick={() => setIsTimerRunning(false)}
                  className="px-6 py-2 rounded-[20px] border-2 transition-all"
                  style={{ borderColor: '#464A63', color: '#464A63' }}
                >
                  Pause
                </button>
                <button
                  onClick={handleExtendTimer}
                  className="px-6 py-2 rounded-[20px] text-white transition-all"
                  style={{ backgroundColor: '#464A63' }}
                >
                  +10 min
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Presence Board */}
        <div className="glass-card p-6">
          <h2 className="text-xl font-semibold text-[#464A63] mb-4">Who's Focusing Right Now</h2>
          <p className="text-sm text-[#4A5565] mb-6">
            {sortedParticipants.length + 1} students present
          </p>

          <div className="space-y-3">
            {/* Other Participants */}
            {sortedParticipants.map((participant) => {
              const initials = participant.name
                .split(' ')
                .map((n) => n[0])
                .join('');
              
              return (
                <div
                  key={participant.id}
                  className="flex items-center justify-between p-4 rounded-[20px] bg-white border border-gray-200"
                >
                  <div className="flex items-center gap-3">
                    <div
                      className="w-10 h-10 rounded-full flex items-center justify-center text-white font-semibold"
                      style={{ backgroundColor: '#464A63' }}
                    >
                      {initials}
                    </div>
                    <div>
                      <div className="font-semibold text-[#464A63]">{participant.name}</div>
                      <div className="text-sm text-[#4A5565]">{getTimeLabel(participant.minutesPresent)}</div>
                    </div>
                  </div>
                </div>
              );
            })}

            {/* You */}
            <div className="flex items-center justify-between p-4 rounded-[20px]" style={{ backgroundColor: '#DAE77B' }}>
              <div className="flex items-center gap-3">
                <div
                  className="w-10 h-10 rounded-full flex items-center justify-center text-white font-semibold"
                  style={{ backgroundColor: '#CD7542' }}
                >
                  Me
                </div>
                <div>
                  <div className="font-semibold text-[#464A63]">You</div>
                  <div className="text-sm text-[#4A5565]">{getTimeLabel(myTimePresent)}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Exit Reflection Modal */}
      <AnimatePresence>
        {showExitModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50"
            onClick={() => setShowExitModal(false)}
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              onClick={(e) => e.stopPropagation()}
              className="bg-white rounded-[20px] max-w-md w-full p-8"
            >
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold text-[#464A63]">Before you go...</h2>
                <button
                  onClick={() => setShowExitModal(false)}
                  className="p-2 hover:bg-gray-100 rounded-lg transition-all"
                >
                  <X className="w-6 h-6 text-[#464A63]" />
                </button>
              </div>

              <p className="text-[#4A5565] text-center mb-6">
                Do you feel less stuck now?
              </p>

              <div className="space-y-3 mb-6">
                {[
                  { value: 'yes', label: 'Yes', icon: CheckCircle2 },
                  { value: 'a-little', label: 'A little', icon: Minus },
                  { value: 'still-stuck', label: 'Still stuck', icon: CircleDashed },
                ].map((option) => {
                  const IconComponent = option.icon;
                  return (
                    <button
                      key={option.value}
                      onClick={() => setSelectedFeeling(option.value)}
                      className="w-full p-4 rounded-[20px] border-2 transition-all text-left flex items-center gap-3"
                      style={{
                        borderColor: selectedFeeling === option.value ? '#DAE77B' : '#E5E7EB',
                        backgroundColor: selectedFeeling === option.value ? '#DAE77B' : 'white',
                      }}
                    >
                      <IconComponent 
                        className="w-6 h-6" 
                        style={{ color: selectedFeeling === option.value ? '#464A63' : '#4A5565' }}
                      />
                      <span className="font-medium text-[#464A63]">{option.label}</span>
                    </button>
                  );
                })}
              </div>

              <button
                onClick={handleExitComplete}
                disabled={!selectedFeeling}
                className="w-full py-3 px-6 rounded-[20px] text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                style={{ backgroundColor: '#464A63' }}
              >
                Done
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
